//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int id_DanhGia { get; set; }
        public Nullable<int> id_sanPham { get; set; }
        public Nullable<int> id_NguoiDung { get; set; }
        public Nullable<int> diemDanhGia { get; set; }
        public string binhLuan { get; set; }
        public Nullable<System.DateTime> ngayDanhGia { get; set; }
        public Nullable<bool> TrangThaiXoa { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
