//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int id_KhuyenMai { get; set; }
        public string tenMa { get; set; }
        public Nullable<double> phanTramGiam { get; set; }
        public string moTaKhuyenMai { get; set; }
        public Nullable<System.DateTime> ngayHet { get; set; }
        public string trangThai { get; set; }
        public string hinhAnh { get; set; }
        public Nullable<bool> TrangThaiXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
