//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKyThuat
    {
        public int id_ThongSo { get; set; }
        public Nullable<int> id_sanPham { get; set; }
        public string tenThongSo { get; set; }
        public string giaTri { get; set; }
        public Nullable<bool> TrangThaiXoa { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
