//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward
    {
        public long id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<long> province_id { get; set; }
        public long district_id { get; set; }
    
        public virtual district district { get; set; }
    }
}
